#!/usr/bin/env python3
"""
png_to_mode4.py — converts a 240x160 PNG into a C header with a palette of
up to 256 colours and an 8bpp pixel buffer ready for GBA mode 4.

Output:
    static const u16 SPLASH_PALETTE[256] = { ... };  // RGB15
    static const u8  SPLASH_PIXELS[240*160] = { ... };

Usage:
    python3 tools/png_to_mode4.py <in.png> <out.h> [--name SPLASH]
"""
from __future__ import annotations
import argparse
import sys
from PIL import Image

GBA_W = 240
GBA_H = 160
PAL_MAX = 256


def to_rgb15(r: int, g: int, b: int) -> int:
    return ((r >> 3) & 0x1F) | (((g >> 3) & 0x1F) << 5) | (((b >> 3) & 0x1F) << 10)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="input PNG (any mode, will be converted)")
    ap.add_argument("output", help="output .h header")
    ap.add_argument("--name", default="SPLASH", help="prefix for the generated C symbols")
    args = ap.parse_args()

    im = Image.open(args.input).convert("RGBA")
    if im.size != (GBA_W, GBA_H):
        im = im.resize((GBA_W, GBA_H), Image.NEAREST)

    # Quantize to <=256 colours. If the image is already paletted with <=256
    # colours, Image.quantize keeps it as is.
    pal_im = im.convert("RGB").quantize(colors=PAL_MAX, method=Image.MEDIANCUT, dither=Image.NONE)

    raw_pal = pal_im.getpalette() or []
    n_colors = len(raw_pal) // 3
    n_colors = min(n_colors, PAL_MAX)

    # Palette to RGB15. Ensures entry 0 = black (transparent / safe background).
    pal16 = []
    for i in range(PAL_MAX):
        if i < n_colors:
            r = raw_pal[i * 3 + 0]
            g = raw_pal[i * 3 + 1]
            b = raw_pal[i * 3 + 2]
            pal16.append(to_rgb15(r, g, b))
        else:
            pal16.append(0)

    pixels = list(pal_im.getdata())  # already indices in 0..255
    if len(pixels) != GBA_W * GBA_H:
        print(f"warning: pixel count {len(pixels)} != {GBA_W*GBA_H}", file=sys.stderr)

    name = args.name
    lines = []
    push = lines.append
    push("/* Auto-generated by tools/png_to_mode4.py — DO NOT edit by hand. */")
    push(f"/* source: {args.input} */")
    push(f"#ifndef GENERATED_{name}_H")
    push(f"#define GENERATED_{name}_H")
    push("")
    push('#include "../types.h"')
    push("")
    push(f"#define {name}_WIDTH  {GBA_W}")
    push(f"#define {name}_HEIGHT {GBA_H}")
    push(f"#define {name}_PALETTE_LEN 256")
    push("")
    push(f"static const u16 {name}_PALETTE[256] = {{")
    row = []
    for i, c in enumerate(pal16):
        row.append(f"0x{c:04x}")
        if (i % 8) == 7:
            push("    " + ", ".join(row) + ",")
            row = []
    if row:
        push("    " + ", ".join(row) + ",")
    push("};")
    push("")

    # Mode 4 only allows 16-bit writes to VRAM, so we pack as u16
    # (lo + hi<<8 = the next even/odd pixel pair).
    push(f"static const u16 {name}_PIXELS_HALF[{GBA_W*GBA_H//2}] = {{")
    row = []
    for j in range(0, len(pixels), 2):
        lo = pixels[j]
        hi = pixels[j + 1] if j + 1 < len(pixels) else 0
        word = (hi << 8) | lo
        row.append(f"0x{word:04x}")
        if (len(row) % 12) == 0:
            push("    " + ", ".join(row) + ",")
            row = []
    if row:
        push("    " + ", ".join(row) + ",")
    push("};")
    push("")
    push(f"#endif /* GENERATED_{name}_H */")
    push("")

    with open(args.output, "w") as f:
        f.write("\n".join(lines))

    print(f"ok: {args.output}  ({n_colors} colors in palette)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
